[package]
name = "ncxyzero/bifrost"
version = "0.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "Bifrost is a compact networking library for Roblox"
license = "MIT"
